  Resources:
    CognitoAuthorizedRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated:
                  - "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  cognito-identity.amazonaws.com:aud:
                    Ref: IdentityPool
                ForAnyValue:StringLike:
                  cognito-identity.amazonaws.com:amr: authenticated
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSIoTDataAccess
        Path: "/"
        Policies:
          - PolicyName: ${{self:custom.context}}_CognitoAPIGatewayAuthPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - execute-api:Invoke
                  Resource: { "Fn::Join" : ["", ["arn:aws:execute-api:",{"Ref":"AWS::Region"},":",{"Ref":"AWS::AccountId"},":",{"Ref":"ApiGatewayRestApi"},"/*"]] }
          - PolicyName: ${{self:custom.context}}_CognitoIotAuthPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "mobileanalytics:PutEvents"
                    - "cognito-sync:*"
                    - "cognito-identity:*"
                  Resource: "*"
                - Effect: Allow
                  Action: "iot:Connect"
                  Resource: "*"
                - Effect: Allow
                  Action: "iot:Subscribe"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:iot:"
                        - Ref: "AWS::Region"
                        - ":"
                        - Ref: "AWS::AccountId"
                        - ":topicfilter/"
                        - ${{self:custom.iotPublicTopic}}
                - Effect: Allow
                  Action:
                    - "iot:Receive"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:iot:"
                        - Ref: "AWS::Region"
                        - ":"
                        - Ref: "AWS::AccountId"
                        - ":topic/"
                        - ${{self:custom.iotPublicTopic}}

    CognitoUnAuthorizedRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  'cognito-identity.amazonaws.com:aud':
                    Ref: IdentityPool
                'ForAnyValue:StringLike':
                  'cognito-identity.amazonaws.com:amr': unauthenticated
        Policies:
          - PolicyName: ${{self:custom.context}}_CognitoIotUnAuthPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "mobileanalytics:PutEvents"
                    - "cognito-sync:*"
                  Resource: "*"
                - Effect: Allow
                  Action: "iot:Connect"
                  Resource: "*"
                - Effect: Allow
                  Action: "iot:Subscribe"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:iot:"
                        - Ref: "AWS::Region"
                        - ":"
                        - Ref: "AWS::AccountId"
                        - ":topicfilter/"
                        - ${{self:custom.iotPublicTopic}}
                - Effect: Allow
                  Action:
                    - "iot:Receive"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:iot:"
                        - Ref: "AWS::Region"
                        - ":"
                        - Ref: "AWS::AccountId"
                        - ":topic/"
                        - ${{self:custom.iotPublicTopic}}
